{
 "title": "Nacos",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "nacos overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "UP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(nacos_monitor{name=\"configCount\",instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "service count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='serviceCount',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longPolling',instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "config connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='longConnection', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<br/>\n<center>\n<a href=\"https://nacos.io\">\n<img src=\"https://nacos.io/img/nacos.png\" style=\"height: 50px;\" >\n</a>\n</center>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "alert list",
   "type": "alertlist",
   "gridPos": { "h": 12, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "FullGC count",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(jvm_gc_pause_seconds_count{action=\"end of major GC\",instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "ops",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) + sum(rate(grpc_server_requests_seconds_count{instance=~'$instance'}[1m]))"
    }
   ]
  },
  {
   "title": "rt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000 + sum(rate(grpc_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(grpc_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000) / 2"
    }
   ]
  },
  {
   "title": "nacos core monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "service count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='serviceCount',instance=~'$instance'})",
     "legendFormat": "service count"
    }
   ]
  },
  {
   "title": "service provider count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='ipCount',instance=~'$instance'})",
     "legendFormat": "provider count"
    }
   ]
  },
  {
   "title": "service subscriber count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{name='subscriberCount',instance=~'$instance'})",
     "legendFormat": "subscriber count"
    }
   ]
  },
  {
   "title": "config count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='configCount',instance=~'$instance'})",
     "legendFormat": "config count"
    }
   ]
  },
  {
   "title": "config long polling count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(nacos_monitor{name='longPolling',instance=~'$instance'})",
     "legendFormat": "config long polling count"
    }
   ]
  },
  {
   "title": "config listener count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_config_subscriber{instance=~'$instance'}) by (instance)",
     "legendFormat": "config listener count"
    }
   ]
  },
  {
   "title": "rt (HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'.*/cs/configs|.*/ns/instance.*', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'.*/cs/configs|.*/ns/instance.*', instance=~'$instance'}[1m])) by (method,uri) * 1000 > 0"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "ops (HTTP)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'.*/cs/configs|.*/ns/instance.*', instance=~'$instance'}[1m])) > 0"
    },
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "naming push task pending count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"naming\",name=\"pushPendingTaskCount\",instance=~'$instance'})",
     "legendFormat": "pending task count"
    }
   ]
  },
  {
   "title": "rt (GRPC)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_requests_seconds_sum{instance=~'$instance'}[1m])/rate(grpc_server_requests_seconds_count{ instance=~'$instance'}[1m])) by (requestClass) * 1000 > 0"
    },
    {
     "expr": "sum(rate(grpc_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(grpc_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "ops (GRPC)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_requests_seconds_sum{instance=~'$instance'}[1m])) by (requestClass) > 0"
    },
    {
     "expr": "sum(rate(grpc_server_requests_seconds_sum{instance=~'$instance'}[1m]))",
     "legendFormat": "all"
    }
   ]
  },
  {
   "title": "config push task pending count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"config\",name=\"notifyClientTask\",instance=~'$instance'})",
     "legendFormat": "pending task count"
    }
   ]
  },
  {
   "title": "nacos basic monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100",
     "legendFormat": "cpu usage"
    }
   ]
  },
  {
   "title": "heap memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100",
     "legendFormat": "heap memory usage"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(increase(jvm_gc_pause_seconds_count{instance=~'$instance'}[1m])) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "GRPC connection count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"core\",name=\"longConnection\",instance=~'$instance'}) by (instance)",
     "legendFormat": "grpc connection count"
    }
   ]
  },
  {
   "title": "GRPC Thread Pool",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grpc_server_executor{module=\"core\",type=\"grpcSdkServer\",instance=~'$instance',name=\"poolSize\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(grpc_server_executor{module=\"core\",type=\"grpcSdkServer\",instance=~'$instance',name=\"maximumPoolSize\"}) by (name)",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg(grpc_server_executor{module=\"core\",type=\"grpcSdkServer\",instance=~'$instance',name=\"activeCount\"}) by (name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GRPC request queue",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(grpc_server_executor{module=\"core\",type=\"grpcSdkServer\",instance=~'$instance',name=\"inQueueTaskCount\"}) by (name)",
     "legendFormat": "request queue size"
    }
   ]
  }
 ]
}