{
 "title": "Nacos-v2",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "instance", "label": "instance", "query": "label_values(instance)" }
  ]
 },
 "panels": [
  {
   "title": "nacos monitor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "service count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{module=\"naming\",name=\"serviceCount\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ip count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{module=\"naming\",name=\"ipCount\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "config count",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{module=\"config\",name=\"configCount\", instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "long polling",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"config\",name=\"longPolling\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "config push total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"config\",name='getConfig', instance=~'$instance'}) by (name)"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "<html>\n<body>\n<center>\n<a href=\"https://nacos.io\">\n<img src=\"https://nacos.io/img/nacos_colorful.png\" style=\"height: 50px;\" >\n</a>\n</center>\n</body>\n</html>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_cpu_usage{instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "memory",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\", instance=~'$instance'})/sum(jvm_memory_max_bytes{area=\"heap\", instance=~'$instance'}) * 100"
    }
   ]
  },
  {
   "title": "alert list",
   "type": "alertlist",
   "gridPos": { "h": 16, "w": 6, "x": 18, "y": 4 },
   "targets": [
    {}
   ]
  },
  {
   "title": "threads",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(system_load_average_1m{instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "notifyRt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(nacos_timer_seconds_sum{module=\"config\",name=\"notifyRt\",instance=~'$instance'}[1m]))/sum(rate(nacos_timer_seconds_count{module=\"config\",name=\"notifyRt\",instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rt",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "qps",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])"
    }
   ]
  },
  {
   "title": "avgPushCost",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 9, "x": 9, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(nacos_monitor{module=\"naming\",name='avgPushCost', instance=~'$instance'})"
    }
   ]
  },
  {
   "title": "nacos detail",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "rt",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{uri=~'/v1/cs/configs|/nacos/v1/ns', instance=~'$instance'}[1m])/rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri) * 1000"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_sum{instance=~'$instance'}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~'$instance'}[1m])) * 1000",
       "legendFormat": "all"
      }
     ]
    },
    {
     "title": "long polling",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 2 },
     "repeat": "group",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nacos_monitor{module=\"config\",name='longPolling', instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "load 1m",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(system_load_average_1m{instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "qps",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(http_server_requests_seconds_count{uri=~'/v1/cs/configs|/nacos/v1/ns/instance|/nacos/v1/ns/health', instance=~'$instance'}[1m])) by (method,uri)"
      },
      {
       "expr": "sum(rate(http_server_requests_seconds_count[1m]))"
      }
     ]
    },
    {
     "title": "leaderStatus",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nacos_monitor{module=\"naming\",name='leaderStatus', instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "avgPushCost",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nacos_monitor{module=\"naming\",name='avgPushCost', instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "maxPushCost",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(nacos_monitor{module=\"naming\",name='maxPushCost', instance=~'$instance'})"
      }
     ]
    },
    {
     "title": "config statistics",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(nacos_monitor{module=\"config\",name='publish', instance=~'$instance'}) by (name)",
       "legendFormat": "publish config"
      },
      {
       "expr": "sum(nacos_monitor{module=\"config\",name='getConfig', instance=~'$instance'}) by (name)",
       "legendFormat": "get config"
      }
     ]
    },
    {
     "title": "health check",
     "type": "timeseries",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(nacos_monitor{module=\"naming\",name=~'.*HealthCheck', instance=~'$instance'}[1m])) by (name) * 60"
      }
     ]
    }
   ]
  },
  {
   "title": "nacos alert",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {}
   ]
  },
  {
   "title": "cpu alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "max(system_cpu_usage) * 100" }
   ]
  },
  {
   "title": "load  alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "max(system_load_average_1m)" }
   ]
  },
  {
   "title": "memory alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\"})/sum(jvm_memory_max_bytes{area=\"heap\"}) * 100"
    }
   ]
  },
  {
   "title": "threads alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(jvm_threads_daemon_threads)"
    }
   ]
  },
  {
   "title": "gc alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(rate(jvm_gc_pause_seconds_count{action=\"end of major GC\",instance=~\"$instance\"}[5m])) * 300"
    }
   ]
  },
  {
   "title": "notify task alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"config\",name='notifyTask',instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "rt alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_sum{instance=~\"$instance\"}[1m]))/sum(rate(http_server_requests_seconds_count{instance=~\"$instance\"}[1m])) * 1000"
    }
   ]
  },
  {
   "title": "long polling alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(nacos_monitor{module=\"config\",name='longPolling',instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "config unhealth exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{module=\"config\",name='unhealth',instance=~\"$instance\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "db exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{module=\"config\",name='db',instance=~\"$instance\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "failed push alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(nacos_monitor{module=\"naming\",name='failedPush',instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "illegalArgument exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{module=\"config\",name='illegalArgument',instance=~\"$instance\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming disk usage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "disk_free_bytes{instance=~\"$instance\"} / disk_total_bytes{instance=~\"$instance\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "config notify exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{module=\"config\",name='configNotify',instance=~\"$instance\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "naming leader send beat failed exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{module=\"naming\",name='leaderSendBeatFailed',instance=~\"$instance\"}[1m])) * 60"
    }
   ]
  },
  {
   "title": "nacos exception alert",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(nacos_exception_total{name='nacos'}[1m])) * 60"
    }
   ]
  }
 ]
}